version: '3.8'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/app
      - HTTP_PORT=3000
      - FINNHUB_API_KEY=ciqlqj9r01qjff7cr300ciqlqj9r01qjff7cr30g
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
