export enum ErrorCodes {
  SYMBOL_DOES_NOT_EXIST = 'SYMBOL_DOES_NOT_EXIST',
  EXTERNAL_API_ERROR = 'EXTERNAL_API_ERROR',
  ALREADY_WATCHING_SYMBOL = 'ALREADY_WATCHING_SYMBOL',
  WATCH_NOT_STARTED = 'WATCH_NOT_STARTED',
  NO_DATA = 'NO_DATA',
}
